[platformio]
src_dir = .

[env:cardputer-adv]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = dio
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_src_filter = +<emf-meter.ino.cpp>
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    m5stack/M5Cardputer@1.1.1
    m5stack/M5Unified@0.2.22
    m5stack/M5GFX@0.2.29
lib_ignore = LibSSH-ESP32, IRremote
monitor_speed = 115200
